-- Create dedicated CDC user and schema
-- Run as SYSDBA

-- Create CDC user
CREATE USER DBZUSER IDENTIFIED BY dbzpassword
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

-- Grant necessary privileges
GRANT CONNECT TO DBZUSER;
GRANT RESOURCE TO DBZUSER;
GRANT CREATE SESSION TO DBZUSER;
GRANT CREATE TABLE TO DBZUSER;
GRANT CREATE SEQUENCE TO DBZUSER;

-- Grant LogMiner privileges
GRANT SELECT ON V_$LOGMNR_CONTENTS TO DBZUSER;
GRANT SELECT ON V_$LOGMNR_LOGS TO DBZUSER;
GRANT SELECT ON V_$LOG TO DBZUSER;
GRANT SELECT ON V_$LOG_HISTORY TO DBZUSER;
GRANT SELECT ON V_$LOGFILE TO DBZUSER;
GRANT SELECT ON V_$ARCHIVED_LOG TO DBZUSER;
GRANT SELECT ON V_$DATABASE TO DBZUSER;
GRANT EXECUTE_CATALOG_ROLE TO DBZUSER;
GRANT SELECT ANY TRANSACTION TO DBZUSER;
GRANT FLASHBACK ANY TABLE TO DBZUSER;
GRANT SELECT ANY TABLE TO DBZUSER;
GRANT LOGMINING TO DBZUSER;

-- Enable supplemental logging at database level
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

PROMPT User DBZUSER created successfully

