-- Create CUSTOMERS table in DBZUSER schema
-- Connect as DBZUSER

CREATE TABLE CUSTOMERS (
  ID NUMBER(19,0) NOT NULL,
  FIRST_NAME VARCHAR2(255),
  LAST_NAME VARCHAR2(255),
  EMAIL VARCHAR2(255),
  CONSTRAINT CUSTOMERS_PK PRIMARY KEY (ID)
);

-- Enable supplemental logging
ALTER TABLE CUSTOMERS ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;

-- Insert test data
INSERT INTO CUSTOMERS VALUES (1, 'John', 'Doe', 'john@example.com');
INSERT INTO CUSTOMERS VALUES (2, 'Jane', 'Smith', 'jane@example.com');
INSERT INTO CUSTOMERS VALUES (3, 'Bob', 'Johnson', 'bob@example.com');
COMMIT;

-- Gather statistics
EXEC DBMS_STATS.GATHER_TABLE_STATS('DBZUSER', 'CUSTOMERS');

-- Verify
SELECT 'Table created with ' || COUNT(*) || ' rows' FROM CUSTOMERS;
SELECT 'Primary key: ' || CONSTRAINT_NAME FROM USER_CONSTRAINTS WHERE TABLE_NAME='CUSTOMERS' AND CONSTRAINT_TYPE='P';
SELECT 'Supplemental logging: ' || COUNT(*) || ' log groups' FROM USER_LOG_GROUPS WHERE TABLE_NAME='CUSTOMERS';

PROMPT
PROMPT DBZUSER.CUSTOMERS table ready for CDC

