-- =====================================================
-- Grant LogMiner Permissions to SYSTEM User
-- =====================================================
-- This grants all necessary permissions for Debezium CDC
-- Run as SYSDBA

-- LogMiner permissions
GRANT SELECT ON V_$LOGMNR_CONTENTS TO SYSTEM;
GRANT SELECT ON V_$LOGMNR_LOGS TO SYSTEM;
GRANT SELECT ON V_$LOG TO SYSTEM;
GRANT SELECT ON V_$LOG_HISTORY TO SYSTEM;
GRANT SELECT ON V_$LOGFILE TO SYSTEM;
GRANT SELECT ON V_$ARCHIVED_LOG TO SYSTEM;
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO SYSTEM;
GRANT SELECT ON V_$DATABASE TO SYSTEM;
GRANT SELECT ON V_$THREAD TO SYSTEM;
GRANT SELECT ON V_$PARAMETER TO SYSTEM;
GRANT SELECT ON V_$NLS_PARAMETERS TO SYSTEM;
GRANT SELECT ON V_$TIMEZONE_NAMES TO SYSTEM;
GRANT SELECT ON V_$TRANSACTION TO SYSTEM;
GRANT SELECT ON V_$ARCHIVE_DEST TO SYSTEM;

-- Dictionary views
GRANT SELECT ON DBA_TABLESPACES TO SYSTEM;
GRANT SELECT ON DBA_OBJECTS TO SYSTEM;
GRANT SELECT ON DBA_USERS TO SYSTEM;

-- Catalog role for LogMiner
GRANT EXECUTE_CATALOG_ROLE TO SYSTEM;

-- Additional CDC permissions
GRANT SELECT ANY TRANSACTION TO SYSTEM;
GRANT FLASHBACK ANY TABLE TO SYSTEM;

-- LogMining privilege (Oracle 19c+)
BEGIN
  EXECUTE IMMEDIATE 'GRANT LOGMINING TO SYSTEM';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -990 THEN
      DBMS_OUTPUT.PUT_LINE('LOGMINING privilege not available in this Oracle version (ignore this error)');
    ELSE
      RAISE;
    END IF;
END;
/

-- Verify grants
SELECT GRANTEE, PRIVILEGE
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'SYSTEM'
  AND (PRIVILEGE LIKE '%TRANSACTION%'
    OR PRIVILEGE LIKE '%FLASHBACK%'
    OR PRIVILEGE LIKE '%LOGMINING%')
ORDER BY PRIVILEGE;

PROMPT
PROMPT ===================================================
PROMPT LogMiner permissions granted to SYSTEM user
PROMPT ===================================================

