-- Grant all necessary V$ views access to DBZUSER for Debezium Oracle Connector
-- Run as SYSDBA

-- Archive log views
GRANT SELECT ON V_$ARCHIVE_DEST_STATUS TO DBZUSER;
GRANT SELECT ON V_$ARCHIVE_DEST TO DBZUSER;

-- Redo log and thread views (required for LogMiner)
GRANT SELECT ON V_$THREAD TO DBZUSER;
GRANT SELECT ON V_$LOG TO DBZUSER;
GRANT SELECT ON V_$LOG_HISTORY TO DBZUSER;
GRANT SELECT ON V_$LOGFILE TO DBZUSER;
GRANT SELECT ON V_$ARCHIVED_LOG TO DBZUSER;

-- LogMiner views
GRANT SELECT ON V_$LOGMNR_CONTENTS TO DBZUSER;
GRANT SELECT ON V_$LOGMNR_LOGS TO DBZUSER;

-- Database and session views
GRANT SELECT ON V_$DATABASE TO DBZUSER;
GRANT SELECT ON V_$PARAMETER TO DBZUSER;
GRANT SELECT ON V_$NLS_PARAMETERS TO DBZUSER;
GRANT SELECT ON V_$TIMEZONE_NAMES TO DBZUSER;
GRANT SELECT ON V_$TRANSACTION TO DBZUSER;

-- Session statistics views (for monitoring)
GRANT SELECT ON V_$STATNAME TO DBZUSER;
GRANT SELECT ON V_$MYSTAT TO DBZUSER;
GRANT SELECT ON V_$SYSSTAT TO DBZUSER;
GRANT SELECT ON V_$SESSION TO DBZUSER;

-- Dictionary views
GRANT SELECT ON DBA_TABLESPACES TO DBZUSER;
GRANT SELECT ON DBA_OBJECTS TO DBZUSER;
GRANT SELECT ON DBA_USERS TO DBZUSER;

-- Additional views that might be needed
GRANT SELECT ON V_$INSTANCE TO DBZUSER;
GRANT SELECT ON V_$VERSION TO DBZUSER;

PROMPT All V$ and DBA views granted to DBZUSER for Debezium CDC

